/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskPO } from './taskPO';

export interface ProjectPO {
  /** Unique identifier of the project */
  readonly id?: number;
  /** Title of the project */
  title: string;
  /** List of tasks belonging to the project */
  tasks?: TaskPO[];
}
