/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskDto } from './taskDto';

export interface ProjectDto {
  id?: number;
  title?: string;
  tasks?: TaskDto[];
}
