/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TaskDtoStatus = typeof TaskDtoStatus[keyof typeof TaskDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskDtoStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
} as const;
