/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TaskPOStatus = typeof TaskPOStatus[keyof typeof TaskPOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskPOStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
} as const;
