/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskPOStatus } from './taskPOStatus';
import type { ProjectPO } from './projectPO';
import type { UserPO } from './userPO';

export interface TaskPO {
  /** Unique identifier of the task */
  readonly id?: number;
  /** Title of the task */
  title: string;
  /** Description of the task */
  description?: string;
  /** Status of the task. Available status are OPEN, IN PROGRESS and DONE */
  status: TaskPOStatus;
  /** The project belonging to the task */
  project?: ProjectPO;
  /** List of users belonging to the task */
  users?: UserPO[];
}
