/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskPOStatus } from './taskPOStatus';
import type { ProjectPO } from './projectPO';
import type { UserPO } from './userPO';

export interface TaskPO {
  id?: number;
  title?: string;
  description?: string;
  status?: TaskPOStatus;
  project?: ProjectPO;
  users?: UserPO[];
}
