/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskPO } from './taskPO';

export interface UserPO {
  id?: number;
  firstName?: string;
  lastName?: string;
  tasks?: TaskPO[];
}
