/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskPO } from './taskPO';

export interface UserPO {
  /** Unique identifier of the user */
  readonly id?: number;
  /** Firstname of the user */
  firstName: string;
  /** Lastname of the user */
  lastName: string;
  tasks?: TaskPO[];
}
