/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  ProjectDto
} from '.././model';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class ProjectControllerService {
  private readonly http = inject(HttpClient);
 loadProject<TData = ProjectDto>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 loadProject<TData = ProjectDto>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 loadProject<TData = ProjectDto>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  loadProject<TData = ProjectDto>(
    id: number, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `http://localhost:8080/projects/${id}`,options
    );
  }
 updateProject<TData = void>(id: number,
    projectDto: ProjectDto, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 updateProject<TData = void>(id: number,
    projectDto: ProjectDto, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 updateProject<TData = void>(id: number,
    projectDto: ProjectDto, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  updateProject<TData = void>(
    id: number,
    projectDto: ProjectDto, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.put<TData>(
      `http://localhost:8080/projects/${id}`,
      projectDto,options
    );
  }
 deleteProject<TData = void>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteProject<TData = void>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteProject<TData = void>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteProject<TData = void>(
    id: number, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(
      `http://localhost:8080/projects/${id}`,options
    );
  }
 loadAllProjects<TData = ProjectDto[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 loadAllProjects<TData = ProjectDto[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 loadAllProjects<TData = ProjectDto[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  loadAllProjects<TData = ProjectDto[]>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `http://localhost:8080/projects`,options
    );
  }
 createProject<TData = void>(projectDto: ProjectDto, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 createProject<TData = void>(projectDto: ProjectDto, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 createProject<TData = void>(projectDto: ProjectDto, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  createProject<TData = void>(
    projectDto: ProjectDto, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `http://localhost:8080/projects`,
      projectDto,options
    );
  }
};

export type LoadProjectClientResult = NonNullable<ProjectDto>
export type UpdateProjectClientResult = NonNullable<void>
export type DeleteProjectClientResult = NonNullable<void>
export type LoadAllProjectsClientResult = NonNullable<ProjectDto[]>
export type CreateProjectClientResult = NonNullable<void>
