/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  UserDto
} from '.././model';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class UserControllerService {
  private readonly http = inject(HttpClient);
 loadUser<TData = UserDto>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 loadUser<TData = UserDto>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 loadUser<TData = UserDto>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  loadUser<TData = UserDto>(
    id: number, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `http://localhost:8080/users/${id}`,options
    );
  }
 updateUser<TData = void>(id: number,
    userDto: UserDto, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 updateUser<TData = void>(id: number,
    userDto: UserDto, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 updateUser<TData = void>(id: number,
    userDto: UserDto, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  updateUser<TData = void>(
    id: number,
    userDto: UserDto, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.put<TData>(
      `http://localhost:8080/users/${id}`,
      userDto,options
    );
  }
 deleteUser<TData = void>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteUser<TData = void>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteUser<TData = void>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteUser<TData = void>(
    id: number, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(
      `http://localhost:8080/users/${id}`,options
    );
  }
 loadAllUsers<TData = UserDto[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 loadAllUsers<TData = UserDto[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 loadAllUsers<TData = UserDto[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  loadAllUsers<TData = UserDto[]>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `http://localhost:8080/users`,options
    );
  }
 createUser<TData = void>(userDto: UserDto, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 createUser<TData = void>(userDto: UserDto, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 createUser<TData = void>(userDto: UserDto, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  createUser<TData = void>(
    userDto: UserDto, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `http://localhost:8080/users`,
      userDto,options
    );
  }
};

export type LoadUserClientResult = NonNullable<UserDto>
export type UpdateUserClientResult = NonNullable<void>
export type DeleteUserClientResult = NonNullable<void>
export type LoadAllUsersClientResult = NonNullable<UserDto[]>
export type CreateUserClientResult = NonNullable<void>
